# Generated by Django 4.0.6 on 2022-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kategoria', models.CharField(max_length=100, null=True)),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['kategoria'],
            },
        ),
    ]
