# Generated by Django 4.0.6 on 2022-09-05 12:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0003_alter_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rozstrzygniecia', models.DateField()),
                ('sygnatura', models.CharField(max_length=30)),
                ('sad', models.CharField(max_length=30)),
                ('rodzaj_rozstrzygniecia', models.CharField(max_length=30)),
                ('nazwa_przedsiebiorcy', models.CharField(max_length=100)),
                ('zakres', models.CharField(max_length=30)),
                ('slowa_kluczowe', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Kara / Mustafa'), (2, 'Kara / Bardzo Poważna'), (3, 'Kara / Błędny przychód'), (10000, 'Nowa / Nowy tag'), (10001, 'Nowa / Nowy Nowy dzień'), (10002, 'Nowa / Głowa'), (10003, 'Nowa / NGO'), (10004, 'Nowa / Mecz'), (10005, 'Nowa / Gem'), (10006, 'Nowa / Set'), (4, 'Sąd / Sąd Najwyższy'), (5, 'Sąd / Sąd Apelacyjny')], max_length=51, null=True)),
                ('dotyczy_wyroku_post', models.CharField(max_length=400)),
                ('nr_decyzji_post', models.CharField(max_length=30)),
                ('data_wydania_dec_post', models.DateField()),
                ('wyrok_doc', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('wyrok_pdf', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('praktyki_klauzule', models.CharField(max_length=5000)),
                ('glowne_zarzuty', models.CharField(max_length=8000)),
                ('tezy_sadu', models.CharField(max_length=10000)),
            ],
        ),
    ]
