# Generated by Django 4.0.6 on 2022-09-06 09:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0004_wpis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='slowa_kluczowe',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(10000, 'Nowa / Nowy tag'), (10001, 'Nowa / Nowy Nowy dzień'), (10002, 'Nowa / Głowa'), (10003, 'Nowa / NGO'), (10004, 'Nowa / Mecz'), (10005, 'Nowa / Gem'), (10006, 'Nowa / Set')], max_length=41, null=True),
        ),
    ]
