# Generated by Django 4.0.6 on 2022-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0005_alter_wpis_slowa_kluczowe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_dec', models.DateField(default=None)),
                ('act_signature', models.CharField(default=None, max_length=30)),
                ('type_of_dec', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
                ('previous_dec', models.CharField(max_length=400)),
                ('source_dec', models.CharField(max_length=30)),
                ('date_of_source_dec', models.DateField()),
                ('act_doc', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('act_pdf', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('subject_of_act', models.CharField(max_length=5000)),
                ('main_allegations', models.CharField(max_length=8000)),
                ('court_theses', models.CharField(max_length=10000)),
                ('quotes', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['industry'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Wpis',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['category']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='kategoria',
            new_name='category',
        ),
    ]
