# Generated by Django 4.0.6 on 2022-09-27 09:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0006_court_entry_industry_scope_delete_wpis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-scope']},
        ),
        migrations.AddField(
            model_name='entry',
            name='court',
            field=models.CharField(choices=[('SN', 'Sąd Najwyższy'), ('SA', 'Sąd Apelacyjny'), ('SOKIK', 'Sąd Ochrony Konkurencji i Konsumentów'), ('NSA', 'Naczelny Sąd Administracyjny'), ('WSA', 'Wojewódzki Sąd Administracyjny'), ('TSUE', 'Trybunał Sprawiedliwości UE')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='industry',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2industry', 'Bankowość'), ('1industry', 'E-commerce'), ('3industry', 'Odzież - handel detaliczny')], max_length=29, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='key_words',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(10001, 'Kontakt z konsumentem / Reklama'), (10002, 'Kontakt z konsumentem / Reklamacja'), (10003, 'Kontakt z konsumentem / Marketing bezpośredni'), (10004, 'Przedmiot rozstrzygnięcia / Kara pieniężna'), (10005, 'Przedmiot rozstrzygnięcia / Komunikacja-Publikacja'), (10006, 'Przedmiot rozstrzygnięcia / Rekompensata'), (10010, 'Przedmiot rozstrzygnięcia / Rygor natychmiastowej wykonalności'), (10011, 'Przedmiot rozstrzygnięcia / Nieudzielenie informacji'), (10000, 'Zarzuty strony / Kumulacja praktyk'), (10007, 'Zarzuty strony / Nieuwzględnienie wniosku o wydanie decyzji zobowiązującej'), (10008, 'Zarzuty strony / Odpowiedzialność za wykonawcę-agenta'), (10009, 'Zarzuty strony / Podwójne karanie')], max_length=71, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='scope',
            field=models.CharField(choices=[('1scope', 'Zbiorowy Interes Konsumentów'), ('2scope', 'Konkurencja'), ('4scope', 'Klauzule Abuzywne'), ('3scope', 'Inne')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='court',
            field=models.CharField(max_length=50),
        ),
    ]
