# Generated by Django 4.0.6 on 2022-09-27 10:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0007_alter_scope_options_entry_court_entry_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_of_source_dec',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='industry',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2industry', 'Bankowość'), ('1industry', 'E-commerce'), ('4industry', 'Inne'), ('3industry', 'Odzież - handel detaliczny')], max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='key_words',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(10001, 'Kontakt z konsumentem / Reklama'), (10002, 'Kontakt z konsumentem / Reklamacja'), (10003, 'Kontakt z konsumentem / Marketing bezpośredni'), (10004, 'Przedmiot rozstrzygnięcia / Kara pieniężna'), (10005, 'Przedmiot rozstrzygnięcia / Komunikacja-Publikacja'), (10006, 'Przedmiot rozstrzygnięcia / Rekompensata'), (10010, 'Przedmiot rozstrzygnięcia / Rygor natychmiastowej wykonalności'), (10011, 'Przedmiot rozstrzygnięcia / Nieudzielenie informacji'), (10013, 'Zagadnienia pozostałe / BIP - informacja publiczna'), (10000, 'Zarzuty strony / Kumulacja praktyk'), (10007, 'Zarzuty strony / Nieuwzględnienie wniosku o wydanie decyzji zobowiązującej'), (10008, 'Zarzuty strony / Odpowiedzialność za wykonawcę-agenta'), (10009, 'Zarzuty strony / Podwójne karanie')], max_length=77, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='previous_dec',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='entry',
            name='source_dec',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
