# Generated by Django 4.0.6 on 2022-09-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0008_alter_entry_date_of_source_dec_alter_entry_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_of_source_dec',
            field=models.DateField(blank=True, null=True),
        ),
    ]
