# Generated by Django 4.0.6 on 2022-09-27 12:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0011_alter_entry_industry_alter_entry_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='industry',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', 'Bankowość'), ('1', 'E-commerce'), ('4', 'Inne'), ('3', 'Odzież - handel detaliczny')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='scope',
            field=models.CharField(choices=[('1', 'Zbiorowy Interes Konsumentów'), ('2', 'Konkurencja'), ('4', 'Klauzule Abuzywne'), ('3', 'Inne')], max_length=30, null=True),
        ),
    ]
