# Generated by Django 4.0.6 on 2022-09-27 13:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0012_alter_entry_industry_alter_entry_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='industry',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2industry', 'Bankowość'), ('1industry', 'E-commerce'), ('4industry', 'Inne'), ('3industry', 'Odzież - handel detaliczny')], max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='scope',
            field=models.CharField(choices=[('1scope', 'Zbiorowy Interes Konsumentów'), ('2scope', 'Konkurencja'), ('4scope', 'Klauzule Abuzywne'), ('3scope', 'Inne')], max_length=30, null=True),
        ),
    ]
