# Generated by Django 4.0.6 on 2022-09-28 12:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0013_alter_entry_industry_alter_entry_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='related_acts',
            field=models.ManyToManyField(to='baza_2_core.entry'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='entry',
            name='key_words',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(10001, 'Kontakt z konsumentem / Reklama'), (10002, 'Kontakt z konsumentem / Reklamacja'), (10003, 'Kontakt z konsumentem / Marketing bezpośredni'), (10004, 'Przedmiot rozstrzygnięcia / Kara pieniężna'), (10005, 'Przedmiot rozstrzygnięcia / Komunikacja-Publikacja'), (10006, 'Przedmiot rozstrzygnięcia / Rekompensata'), (10010, 'Przedmiot rozstrzygnięcia / Rygor natychmiastowej wykonalności'), (10011, 'Przedmiot rozstrzygnięcia / Nieudzielenie informacji'), (10014, 'Przedmiot rozstrzygnięcia (wypowiedź sądu) / Kara pieniężna'), (10015, 'Przedmiot rozstrzygnięcia (wypowiedź sądu) / Komunikacja-Publikacja'), (10016, 'Przedmiot rozstrzygnięcia (wypowiedź sądu) / Rekompensata'), (10017, 'Przedmiot rozstrzygnięcia (wypowiedź sądu) / Rygor natychmiastowej wykonalności'), (10018, 'Przedmiot rozstrzygnięcia (wypowiedź sądu) / Nieudzielenie informacji'), (10013, 'Zagadnienia pozostałe / BIP - informacja publiczna'), (10000, 'Zarzuty strony / Kumulacja praktyk'), (10007, 'Zarzuty strony / Nieuwzględnienie wniosku o wydanie decyzji zobowiązującej'), (10008, 'Zarzuty strony / Odpowiedzialność za wykonawcę-agenta'), (10009, 'Zarzuty strony / Podwójne karanie')], max_length=107, null=True),
        ),
    ]
