# Generated by Django 4.0.6 on 2022-09-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_2_core', '0014_entry_related_acts_alter_entry_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='related_acts',
            field=models.ManyToManyField(blank=True, null=True, to='baza_2_core.entry'),
        ),
    ]
